### ISSUE TITLE
Add member profile page and link to members page 

### ISSUE THREAD

**Issue by PettraV** [CodeCatz/TrackCat#138]

**Comment by PettraV** [comment]
He girls, sorry for the stupid question, i am  trying to get in :) is this issue in any conflict with any of your issues? thx
@anuschka @livike @mojcas @NinaNinchy @fbbunny

**Comment by goranche** [comment]
@PettraV (and the others): please move discussions like this to the FB group... also, @PettraV, it should be your responsibility to track stuff like this...
