### ISSUE TITLE
Update user profile page

### ISSUE THREAD

**Issue by mojcas** [CodeCatz/TrackCat#142]
Add edit user profile functionality. Have we done anywhere yet the form, to update data in the model, perhaps in any other area? I'm struggling.. check out my branch:
https://github.com/mojcas/TrackCat/tree/update_userprofile
@livike @anuschka @fbbunny - you guys maybe have any ideas how to do this?

**Comment by mojcas** [comment]
Works by on this in PR #143

**Comment by anuschka** [comment]
Hey @mojcas. I haven't done a form yet but I am sure we can do it together :tropical_fish:
