### ISSUE TITLE
Correctly set up a folder for user uploaded pictures

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#144]
Currently, profile pics uploaded by users are stored in the root dir, which is a big no-no. Check out the `MEDIA CONFIGURATION` settings in the [coding-events](https://github.com/codeeu/coding-events/blob/master/codeweekeu/settings.py) repo for reference (and don't forget to add this folder to `.gitignore`!) and then define the destination folder in your UserProfile model (hint: `upload_to=settings.MEDIA_UPLOAD_FOLDER`, see the [Event model](https://github.com/codeeu/coding-events/blob/master/api/models/events.py) for reference).

Also, member images should be removed from `static/img`, as we're now pulling member images from the database (bonus points: move the groupmeet.jpg image from `static/css`into `static/img`).

**Comment by anuschka** [comment]
I will try to do this one :thought_balloon:

**Comment by goranche** [comment]
@anuschka [look at this](http://www.youtube.com/watch?v=2SqojOuP4fk)

**Comment by anuschka** [comment]
@goranche Do :smile:

**Comment by goranche** [comment]
@anuschka, @ialja is this done / fixed?

**Comment by anuschka** [comment]
Yes IMHO :smile_cat:
