### ISSUE TITLE
Make the admin interface more admin-friendly

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#145]
Currently, the /admin UI is filled with things like "UserProfile object", "Project object" and such, which makes it difficult to know what you want to edit. Django offers a lot of flexibility in the way the admin interface is presented, see the [documentation](https://docs.djangoproject.com/en/1.7/ref/contrib/admin/) for more info.

**Comment by anuschka** [comment]
I would give it a try :fishing_pole_and_fish:

**Comment by mojcas** [comment]
@anuschka it works great. Note a new PR #173 changing user profile model, also updating admin.py

**Comment by ialja** [comment]
This issue still needs a bit of work. For example, the ability to change profile picture on user profiles is now missing, and the editing of a user profile is cluttered by Projects, which aren't really needed on this page. When editing projects and tasks, you are still given the option of selecting User profile objects and Project objects without any indication of what you're actually selecting.

So, leaving this issue open for now, looking forward to seeing more improvements!

**Comment by anuschka** [comment]
I'll continue on this one please.

**Comment by ialja** [comment]
Nice job by @anuschka on this one, closing the issue.
