### ISSUE TITLE
FIX COLORS of the template

### ISSUE THREAD

**Issue by fbbunny** [CodeCatz/TrackCat#156]
The suggestion @ialja made with navbar black, footer green as the logo, worked quite ok. Any other suggestions?

**Comment by ialja** [comment]
Oh yes, a much needed issue! :grinning: You could try applying a [Bootstrap theme](http://bootstrapzero.com), so you don't have to do everything from scratch, and then just tweak the details as needed.

**Comment by goranche** [comment]
I second the bootstrap theme thing... much result with (relatively!) little work

**Comment by fbbunny** [comment]
Will do later in the evening

**Comment by ialja** [comment]
There's always improvements to be done, but #182 made the website much cooler already, so closing this issue for now.
