### ISSUE TITLE
Group members on members page 

### ISSUE THREAD

**Issue by anuschka** [CodeCatz/TrackCat#164]
According to Jure's suggestion:
>Django has a method on models with choices, which is:
>.get_FIELD_NAME_display, so in your case you can use member.get_activity_status_display so you >don't need if checkes. Also check forloop.group so you can group them by type.

**Comment by mojcas** [comment]
@anuschka please check updates made in PR #167 to the member page. I removed the repeating  member data from member page, but no grouping of members by activity status is done yet...

**Comment by anuschka** [comment]
@mojcas Is it on branch master?

**Comment by mojcas** [comment]
I've been adding branches (member_issues and profile_image), and also I have pushed to the master what worked well, so to get things pushed to CodeCatz master as well, with this PR (afraid to do much more, coz it'd getting too big).. but so far, yes (member page updates have been pushed to my master).

**Comment by mojcas** [comment]
Done in #214
