### ISSUE TITLE
Change the Login link in navbar to a user menu after login

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#176]
The Login link should display your account info and possibly include links to your profile page, edit profile option and the ability to logout when you're logged in.

@anuschka already did something like this, but it wasn't merged because of design issues. Would be nice to see a PR that just adds this functionality without messing up with the design too much.

**Comment by anuschka** [comment]
I can give it another try (without interfering with design)  if that is ok.

**Comment by ialja** [comment]
Good, just do it! :thumbsup:

**Comment by ialja** [comment]
Done - you could also add the link to the user's profile and the edit profile page in future PR.
