### ISSUE TITLE
We need gallery page with pictures

### ISSUE THREAD

**Issue by MicMacMeow** [CodeCatz/TrackCat#20]
< We need picture section on our page.

**Comment by ialja** [comment]
The Gallery view has been added in #43, but let's add some images to the page, as suggested by @sparkica, as an exercise :) Will leave this open for now.

**Comment by ialja** [comment]
@MicMacMeow any plans on doing this issue? Otherwise it will be closed.

**Comment by ialja** [comment]
Closing this issue, as nothing was done and we don't really need this page just yet.
