### ISSUE TITLE
Fix the div structure of the Events and Members page to be the same as the other pages

### ISSUE THREAD

**Issue by livike** [CodeCatz/TrackCat#240]
In this two pages the wrap div contains the footer. In the rest of the pages the footer is after the wrap div.
This is the reason that if the events or members page have minimal or no content, the footer practically sticks with the navbar. 
Then add the min-height:100% to the wrap div.

**Comment by ialja** [comment]
This is an interestingly specific issue - would be better to just do it and make a PR out of it :)

**Comment by anuschka** [comment]
@livike wrap and footer div are defined in base and not in individual templates.

**Comment by livike** [comment]
@anuschka There was a bug that was fixed in #253 and also in #252 for projects in case when no records to show.
