### ISSUE TITLE
Paragraphs not aligned

### ISSUE THREAD

**Issue by anuschka** [CodeCatz/TrackCat#263]
For an empty database these are not aligned:
- on projects page "There are currently no projects in your projects list."
- on members page "There are no mentors in the group." and "There are no mentors in the group."
- on events page "There are currently no events."

Suggestion: We could uniformly do it the same as for Tasks "There are currently no tasks in tasks list."

**Comment by goranche** [comment]
how is this an enhancement?

**Comment by anuschka** [comment]
... it was a tiny bug :+1:
