### ISSUE TITLE
Project description on project detailed page

### ISSUE THREAD

**Issue by anuschka** [CodeCatz/TrackCat#266]
It would be nice if the project description would be aligned right to the label like other fields on this page.

**Comment by goranche** [comment]
come on... this is a 2 minute task, 5 if you add testing, committing and PR creating to it...
does it really need an issue tagged as enhancement?

**Comment by anuschka** [comment]
:wink: will do

**Comment by anuschka** [comment]
Well it appears the issue is not with the alignment but with all the descriptions when they are longer since they overlap with other elements. I will close this issue since it is obsolete.
