### ISSUE TITLE
Profile pictures don't work on the production website

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#285]

**Comment by anuschka** [comment]
@ialja  Is Amazon S3 Bucket  the way to go for  our profile pictures in production?

**Comment by anuschka** [comment]
You can update your profile pictures :sunny:

**Comment by goranche** [comment]
@anuschka is this linked to any PR? were the changes really only server side?

**Comment by anuschka** [comment]
It was not a PR... the changes were made on my master and then uploaded to heroku. I created a branch "production" on my github account with all the changes made for production.
