### ISSUE TITLE
Mentor and active cats should have the ability to add projects/tasks

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#286]
Currently, only a super user can do that, which isn't really ideal.

**Comment by goranche** [comment]
Not sure active cats should have that ability... I think it might be enough if only mentors could add projects :thought_balloon: 

but still, only admin isn't good enough

**Comment by ialja** [comment]
Mhm, maybe active cats can add tasks or something like that?

**Comment by goranche** [comment]
yup, that I agree with :+1:

**Comment by mojcas** [comment]
To add projects and tasks, as well as change/delete, admin needs to assign permissions.
![userpermissions](https://cloud.githubusercontent.com/assets/9574778/6578674/ccc07b22-c745-11e4-8a77-fa9bbdf1ed17.jpg)

**Comment by ialja** [comment]
@mojcas That's quite an inconvenient way of doing it, to put it mildly.

**Comment by mojcas** [comment]
Agreed. This could be done automatically, to assign permissions, maybe based on status?
Now, admin needs to assign status (change from New Kitten to Active Cat for example), so this is one more manual step for now needed, to assign permissions. 
It was either this, or let any logged in user do it. :fearful:

**Comment by livike** [comment]
Maybe we can solve this by definig a group for Active Cats with desired permissions. Then on status change from New Kitten to Active Cat (the only manual step to do) we can add user to a group programatically.
This way handling the permissions will remain in the admin area by defining groups. The group assignment  to the user will be regulated with our algorithm.
