### ISSUE TITLE
Make the About page about TrackCat, not CodeCatz

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#287]
... and add a link to the [CodeCatz page](http://codecatz.org) somewhere

**Comment by livike** [comment]
True, we have now some more words about TrackCat, however still I don't like it... It's now a strange mix of TrackCat and CodeCatz. I suggest to rewrite the content together at today's meetup...

**Comment by mojcas** [comment]
Done on live site https://trackcat.herokuapp.com/about/
