### ISSUE TITLE
Navigation does not show what page you are on

### ISSUE THREAD

**Issue by mojcas** [CodeCatz/TrackCat#44]
We need to fix the navigation to show what page you are on

**Comment by goranche** [comment]
we really need to stop using "we need ..." in issue titles and/or descriptions :grin:

**Comment by ialja** [comment]
Excellent issue! Will you be working on it, @mojcas? :)

**Comment by mojcas** [comment]
@ialja yes :) but I don't get it ... if we want navigation to be part of base.html, how can it know, what page you are on.. any hints, anyone? :angel: :question:

**Comment by ialja** [comment]
Google is your friend :cat: You're looking for Django highlight active page ... :wink:

**Comment by goranche** [comment]
> any hints, anyone?

do I look like google to you? :angel: :grin: :wink: 
(I'd add bootstrap to the query, in addition to the things @ialja wrote)

**Comment by mojcas** [comment]
@goranche what does this even mean, "add bootstrap to the query" :laughing: 
like @ialja comment better, will try come up with something :dancer:

**Comment by goranche** [comment]
:smile: @ialja gave you some hints on what you're looking for (Django highlight active page)... I would add bootstrap to those, so you'd be searching for "Django bootstrap highlight active page"

> like @ialja comment better

:confounded: :pensive: ok, I'll be quiet from now on...
:wink:

**Comment by ialja** [comment]
Boostrap has a built in class `active` that highlights currently active pages and other stuff - just what we need! :smiley: See: http://getbootstrap.com/components/#nav for examples - note how the `<li>` elements that have `class="active"`differ from the others that don't. So, we basically want Django to figure out where to add the active class to our navigation links.

A pretty neat solution to the problem: http://blog.scur.pl/2012/09/highlighting-current-active-page-django/ + bonus points if you also change all links to various pages to dynamic links using the Django built-in `{% url %}` tag ([see documentation](https://docs.djangoproject.com/en/1.5/ref/templates/builtins/#url)).

**Comment by goranche** [comment]
seems to be fixed by #64, so closing
