### ISSUE TITLE
Fix indentation in css file

### ISSUE THREAD

**Issue by goranche** [CodeCatz/TrackCat#49]
[TrackCat/style.css](https://github.com/CodeCatz/TrackCat/blob/master/static/css/style.css) is indented in a weird way, there are 3 levels of indentation too many... these should be removed

**Comment by anuschka** [comment]
Will get rid of one level.

**Comment by goranche** [comment]
nah, let someone else do it :wink:

**Comment by ialja** [comment]
@anuschka we're sure you can do it, but this is a perfect beginner issue for one of the less experienced kittens :cat:

**Comment by ercchy** [comment]
I think @anuschka should do it, since it is her that introduced the indentation.

**Comment by ialja** [comment]
Looking much better after #50 (yay for team effort!), we can also improve on the little details later. Thanks, @PettraV! :smiley:
