### ISSUE TITLE
create img & js folder in static file

### ISSUE THREAD

**Issue by PettraV** [CodeCatz/TrackCat#54]

**Comment by goranche** [comment]
this isn't really needed until there are actual files to put into those directories
even more, git will not add empty directories into the repository

**Comment by PettraV** [comment]
This was proposed by senior TrackCats and agreed on the meeting

**Comment by goranche** [comment]
that doesn't change the stated fact(s)

**Comment by PettraV** [comment]
it is not empty,  added are 3 img of anuska

**Comment by goranche** [comment]
are you sure you wan't to play the "smartypants" game with me? :smirk:

**Comment by ialja** [comment]
Closing this issue - @PettraV moved existing images to a new img folder with #56, we'll be adding a js folder when needed.
