### ISSUE TITLE
Style the footer with multiple columns, social media icons and better design

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#55]
Combining #36, #45, #46 and overall design improvements into a bigger issue that @anuschka will work ok.

**Comment by PettraV** [comment]
@ialja per agreement with @anuschka, please assign this issue to me, I will do my best to manifest Ana's footer idea :)

**Comment by ialja** [comment]
Great, looking forward to it! :+1:

**Comment by ialja** [comment]
Columns added to footer with #77, so the only thing left to do is adding some social media icons (hint: [Font Awesome](http://fortawesome.github.io/Font-Awesome/) was already included).

**Comment by anuschka** [comment]
I am actually working on it :smile_cat:

**Comment by goranche** [comment]
@PettraV we assigned @anuschka on this for now, so we can keep going forward :wink: 
get well soon :+1:
