### ISSUE TITLE
Add Members in about page and FB links

### ISSUE THREAD

**Issue by PettraV** [CodeCatz/TrackCat#60]

**Comment by goranche** [comment]
is this fixed by #67? can I close it?

also, when doing PRs, don't put the number of an issue (or anything else) into the title... it will not link and not be counted as a reference...
if you need to do that, do it in a comment (or the description)

**Comment by PettraV** [comment]
Jap :) roger  :+1:

**Comment by goranche** [comment]
ok... now on to #68 :smile:
