### ISSUE TITLE
Number of page visits

### ISSUE THREAD

**Issue by senjapollak** [CodeCatz/TrackCat#69]
Add a counter for number of page visits and statistics on visits per day.

**Comment by goranche** [comment]
I don't believe this to be necessary... displaying a counter on the page is not really something that brings a real benefit, and statistics can be collected in other ways (check google analytics for en example)...
and also, this only makes sense, when the site goes live on a publicly accessible server... :wink:

I'm closing this for now

**Comment by goranche** [comment]
or maybe not close it... just so we don't forget about the stats when the site goes live... :blush: 

just no work needs to be done on this for now
