### ISSUE TITLE
Enlarge images on about page and change About us to About CodeCatz

### ISSUE THREAD

**Issue by PettraV** [CodeCatz/TrackCat#73]
added also some beauty corrections of text

**Comment by goranche** [comment]
> added also some beauty corrections of text

this doesn't sound like something you'd write in an issue :wink:

**Comment by PettraV** [comment]
so you do not write this kind of stuff nowhere and just do them?

**Comment by goranche** [comment]
I would put stuff like that in a commit message

**Comment by goranche** [comment]
so, you do the changes, and when you commit them, you describe what you did, pretty much as you did here :wink: 
and as far as I can tell, you've been doing that...

for example this commit message: larger images and font size adjustments
(I would add "on the about page" or something, but still :+1: )

**Comment by PettraV** [comment]
noted :)
