### ISSUE TITLE
Navigation bar "folds" at certain widths

### ISSUE THREAD

**Issue by goranche** [CodeCatz/TrackCat#75]
the navigation bar collapses into a "hamburger" icon when the window is narrow enough, but in between there is a width, where the navigation bar is shows in 2 lines, which breaks the layout...
![screen shot 2015-01-12 at 10 27 30](https://cloud.githubusercontent.com/assets/1487971/5700968/d8fc5c1c-9a45-11e4-83ca-e3fc7881baf2.png)

this is pretty much the same issue that @PettraV is having in #74 where the content is too wide for the navigation bar, causing the layout to fail

possible solutions:

* rethink the navigation bar layout
* make the content smaller
* ...

**Comment by anuschka** [comment]
Is it OK if I try to do this one? I know @mojcas has it her #127 but we need a different layout. Not authenticated users get Projects and Memebers. We can move About, Events, Gallery and Links to a secondary menu and get rid of the Search for now.

**Comment by goranche** [comment]
stop asking, start doing :smile:

**Comment by mojcas** [comment]
@anuschka just do it :smile_cat: In my #127 there are just few changes, I am sure you can merge with your code, and the master, so we can continue... There are plenty more issues :clock12:

**Comment by goranche** [comment]
or create your own PR and we'll see which one fits the needs better, if needed a merge can be done then and there

**Comment by anuschka** [comment]
:hand:

**Comment by ialja** [comment]
Still happens at some widths (768 - 790px), so leaving the issue open. ![screen shot 2015-02-11 at 17 54 59](https://cloud.githubusercontent.com/assets/1607407/6151637/72000222-b217-11e4-8963-a305e0ecf3c7.png)

**Comment by fbbunny** [comment]
I think this issue is solved since design changes

**Comment by ialja** [comment]
You are correct, @fbbunny, good job! :+1:
