### ISSUE TITLE
Add a newsletter and subscription to about page

### ISSUE THREAD

**Issue by PettraV** [CodeCatz/TrackCat#76]
I am thinking to have a newsletter section where links from media about CC would be published. Every time a new link is added, all subscribers would be informed automatically. I sounds awesome to me, but I will need some serious assistance :)

**Comment by ialja** [comment]
Not sure newsletter is the right solutions for this. RSS might be more useful for what you're describing.

**Comment by goranche** [comment]
nah, not needed for now...
and also, a different solution maybe... sometime

**Comment by PettraV** [comment]
okey, some other time with some other page for sure :)
