### ISSUE TITLE
Create model for Users

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#84]
In `api/models.py`, define a model for Users, as discussed during the meetup. 

User attributes to define:

- full name
- GitHub username
- profile picture
- activity level
- website
- bio
- date joined
- date of last login
- date update
- active (yes/no)

**Comment by PettraV** [comment]
I will do this one, okey?

**Comment by ialja** [comment]
Yes, we were thinking about you! :grinning: You can start by checking out the user model definition in our codeeu project: https://github.com/codeeu/coding-events/blob/master/api/models/users.py

It might make sense to create a UserProfile model, as Django already has a built-in [User](https://docs.djangoproject.com/en/1.7/ref/contrib/auth/) model with a bunch of stuff.

**Comment by goranche** [comment]
as @ercchy already wrote in [this comment](https://github.com/CodeCatz/TrackCat/issues/86#issuecomment-70055044), please collaborate with the others, because there will be issues otherwise...

**Comment by ialja** [comment]
Done in #108.
