### ISSUE TITLE
Create model for Projects

### ISSUE THREAD

**Issue by ialja** [CodeCatz/TrackCat#85]
In `api/models.py`, define a model for Projects, as discussed during the meetup. 

Needed attributes:

- project name
- description
- status
- deadline
- date created
- date updated
- owner
- members
- repository links
- tasks
- production website
- test website

**Comment by anuschka** [comment]
Can I try this one as per our model?
![img_20150114_195159](https://cloud.githubusercontent.com/assets/9576281/5747453/692ac60e-9c38-11e4-9851-cb34ff44a765.jpg)

**Comment by goranche** [comment]
as @ercchy already wrote in [this comment](https://github.com/CodeCatz/TrackCat/issues/86#issuecomment-70055044), please collaborate with the others, because there will be issues otherwise...

**Comment by PettraV** [comment]
@anuschka @livike @senjapollak I will start to work on this not before Monday. Please let me know where I have to follow your system as right now I have no idea what they are talking about but I trust the guidance :)

**Comment by ialja** [comment]
Done in #101
