### ISSUE TITLE
Create dashboard for user profile management with Bootstrap

### ISSUE THREAD

**Issue by livike** [CodeCatz/TrackCat#89]

**Comment by sparkica** [comment]
It's very likely you won't be needing this one. Django already has admin covered, no need to implement one by yourself.

**Comment by livike** [comment]
Ok,  just right now thinked about this to ask: The user management form in Django admin will be for all users or only for users with rights to access the admin area?

**Comment by ercchy** [comment]
Good question! 

I think this has yet to be determined, IMO I wold not want everyone to have access to the admin...

**Comment by sparkica** [comment]
User management can be done in different ways: 1) User with proper rights adds a new user via admin interface. Not everyone has access (god forbid!) 2) New users are added via registration process... It's up to you guys how you want to do stuff :)

**Comment by ialja** [comment]
We're talking about at least two different things here. One is how admins manage users, and the other is how a user manages her own profile. I think it's a good idea for @livike to create a form that will be used for users to add/edit their profile info.

**Comment by ercchy** [comment]
@livike can you rename the issue into something like "Create dashboard for user profile management" or something simillar?

**Comment by livike** [comment]
Regardless of which of above methods we chose to add users, I think we need a form page, more like a profile page, where each user can change their personal informations.

**Comment by livike** [comment]
ok :) same things was being said. I'm changing the name of the Issue. Thx.

**Comment by goranche** [comment]
@ercchy , @livike : IMHO dashboard probably isn't the right choice either, as that's a different beast altogether... maybe profile page?

**Comment by ialja** [comment]
A basic edit profile form was added in #99. Closing this issue now, the next step is implementing that using Django forms and models.
