### ISSUE TITLE
The content and the footer are overlapping each other

### ISSUE THREAD

**Issue by livike** [CodeCatz/TrackCat#98]
When content exist in the #wrap div, the content and the footer overlap each other. See projects, about.

**Comment by goranche** [comment]
adding a screenshot might help :wink:

**Comment by livike** [comment]
Home:
![screen shot 2015-01-20 at 15 05 12](https://cloud.githubusercontent.com/assets/6690754/5818416/d16cb656-a0b5-11e4-8acc-720d148471a9.png)

Projects: 
![screen shot 2015-01-20 at 15 06 44](https://cloud.githubusercontent.com/assets/6690754/5818457/0cd3955c-a0b6-11e4-9516-d4bd9c24f03e.png)

**Comment by ialja** [comment]
Doesn't seem to be an issue anymore.
